//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFx.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenFx.Components.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation in {0} resulted in overflow.  This can often happen if Temperature setting is less than one..
        /// </summary>
        internal static string ErrorMsg_BoltzmannTotalOverflow {
            get {
                return ResourceManager.GetString("ErrorMsg_BoltzmannTotalOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or empty..
        /// </summary>
        internal static string ErrorMsg_EmptyList {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity list cannot be empty..
        /// </summary>
        internal static string ErrorMsg_EntityListEmpty {
            get {
                return ResourceManager.GetString("ErrorMsg_EntityListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity has not been initialized yet..
        /// </summary>
        internal static string ErrorMsg_EntityNotInitialized {
            get {
                return ResourceManager.GetString("ErrorMsg_EntityNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent node must belong to a tree before child nodes can be added..
        /// </summary>
        internal static string ErrorMsg_InsertChildNodeWithoutTree {
            get {
                return ResourceManager.GetString("ErrorMsg_InsertChildNodeWithoutTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value is invalid.  Valid values are {1}..
        /// </summary>
        internal static string ErrorMsg_InvalidEnum {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;{0}&apos; must be a fixed integer count greater than 0 or an integral percentage between 1 and 100..
        /// </summary>
        internal static string ErrorMsg_InvalidPopulationReplacementValue {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidPopulationReplacementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; setting must be a valid {1} value.  The value provided was &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorMsg_InvalidTimeLimit {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be greater than or equal to zero..
        /// </summary>
        internal static string ErrorMsg_InvalidWheelSliceSize {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidWheelSliceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is a fixed size and cannot be changed..
        /// </summary>
        internal static string ErrorMsg_ListEntityBase_FixedSize {
            get {
                return ResourceManager.GetString("ErrorMsg_ListEntityBase_FixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item of type &apos;{0}&apos; cannot be casted to type &apos;{1}&apos; that is required by the list..
        /// </summary>
        internal static string ErrorMsg_ListEntityBase_InvalidItemType {
            get {
                return ResourceManager.GetString("ErrorMsg_ListEntityBase_InvalidItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of this list cannot be changed..
        /// </summary>
        internal static string ErrorMsg_ListEntityLengthCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorMsg_ListEntityLengthCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorMsg_MismatchedMinMaxValues {
            get {
                return ResourceManager.GetString("ErrorMsg_MismatchedMinMaxValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not exist a component configuration for component &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMsg_MissingComponentConfiguration {
            get {
                return ResourceManager.GetString("ErrorMsg_MissingComponentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using partially matched crossover is only allowed for two crossover points..
        /// </summary>
        internal static string ErrorMsg_MultiPointCrossoverOperationCrossoverPointValidator_ValidationError {
            get {
                return ResourceManager.GetString("ErrorMsg_MultiPointCrossoverOperationCrossoverPointValidator_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only binary values (zero or one) are allowed..
        /// </summary>
        internal static string ErrorMsg_NonBinaryValueUsed {
            get {
                return ResourceManager.GetString("ErrorMsg_NonBinaryValueUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null item was contained in the list..
        /// </summary>
        internal static string ErrorMsg_NullItemInList {
            get {
                return ResourceManager.GetString("ErrorMsg_NullItemInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMsg_ObjectIsWrongType {
            get {
                return ResourceManager.GetString("ErrorMsg_ObjectIsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of objects to be replaced must be a non-negative integer.  The value provided was &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMsg_PopulationReplacementValue_LessThanZero {
            get {
                return ResourceManager.GetString("ErrorMsg_PopulationReplacementValue_LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of nodes in this collection is fixed and cannot be changed..
        /// </summary>
        internal static string ErrorMsg_TreeNodeCollectionCountError {
            get {
                return ResourceManager.GetString("ErrorMsg_TreeNodeCollectionCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tree node value &apos;{0}&apos; must implement System.IComparable..
        /// </summary>
        internal static string ErrorMsg_TreeNodeValueNotComparable {
            get {
                return ResourceManager.GetString("ErrorMsg_TreeNodeValueNotComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class does not support the use of unique element values..
        /// </summary>
        internal static string ErrorMsg_UseUniqueElementValuesNotSupported {
            get {
                return ResourceManager.GetString("ErrorMsg_UseUniqueElementValuesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be greater or equal to zero and less than or equal to the length..
        /// </summary>
        internal static string ErrorMsg_VariableLengthListEntity_InsertBit_OutOfRange {
            get {
                return ResourceManager.GetString("ErrorMsg_VariableLengthListEntity_InsertBit_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be greater or equal to zero and less than the length..
        /// </summary>
        internal static string ErrorMsg_VariableLengthListEntity_RemoveBit_OutOfRange {
            get {
                return ResourceManager.GetString("ErrorMsg_VariableLengthListEntity_RemoveBit_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm completed..
        /// </summary>
        internal static string MetricLogger_AlgorithmCompleted {
            get {
                return ResourceManager.GetString("MetricLogger_AlgorithmCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm started..
        /// </summary>
        internal static string MetricLogger_AlgorithmStarted {
            get {
                return ResourceManager.GetString("MetricLogger_AlgorithmStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Name: {0}
        ///Metric Value: {1}
        ///Population Index: {2}
        ///Generation Index: {3}.
        /// </summary>
        internal static string MetricLogger_StatTrace {
            get {
                return ResourceManager.GetString("MetricLogger_StatTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree is not set on node..
        /// </summary>
        internal static string NodeTreeNotSet {
            get {
                return ResourceManager.GetString("NodeTreeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population does not have its raw mean value set..
        /// </summary>
        internal static string PopulationRawMeanNotSet {
            get {
                return ResourceManager.GetString("PopulationRawMeanNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population does not have its raw standard deviation value set..
        /// </summary>
        internal static string PopulationRawStandardDeviationNotSet {
            get {
                return ResourceManager.GetString("PopulationRawStandardDeviationNotSet", resourceCulture);
            }
        }
    }
}
