//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StatisticsModel", "FK_StatisticLogs_Runs", "Run", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenFx.ComponentLibrary.Run), "StatisticLog1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenFx.ComponentLibrary.StatisticLog), true)]
[assembly: EdmRelationshipAttribute("StatisticsModel", "FK_StatisticLogs_Statistics", "Statistic", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenFx.ComponentLibrary.StatisticItem), "StatisticLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenFx.ComponentLibrary.StatisticLog), true)]

#endregion

namespace GenFx.ComponentLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StatisticLogContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StatisticLogContext object using the connection string found in the 'StatisticLogContext' section of the application configuration file.
        /// </summary>
        public StatisticLogContext() : base("name=StatisticLogContext", "StatisticLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StatisticLogContext object.
        /// </summary>
        public StatisticLogContext(string connectionString) : base(connectionString, "StatisticLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StatisticLogContext object.
        /// </summary>
        public StatisticLogContext(EntityConnection connection) : base(connection, "StatisticLogContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Run> Runs
        {
            get
            {
                if ((_Runs == null))
                {
                    _Runs = base.CreateObjectSet<Run>("Runs");
                }
                return _Runs;
            }
        }
        private ObjectSet<Run> _Runs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatisticLog> StatisticLogs
        {
            get
            {
                if ((_StatisticLogs == null))
                {
                    _StatisticLogs = base.CreateObjectSet<StatisticLog>("StatisticLogs");
                }
                return _StatisticLogs;
            }
        }
        private ObjectSet<StatisticLog> _StatisticLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatisticItem> StatisticItems
        {
            get
            {
                if ((_StatisticItems == null))
                {
                    _StatisticItems = base.CreateObjectSet<StatisticItem>("StatisticItems");
                }
                return _StatisticItems;
            }
        }
        private ObjectSet<StatisticItem> _StatisticItems;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Runs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRuns(Run run)
        {
            base.AddObject("Runs", run);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatisticLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatisticLogs(StatisticLog statisticLog)
        {
            base.AddObject("StatisticLogs", statisticLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatisticItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatisticItems(StatisticItem statisticItem)
        {
            base.AddObject("StatisticItems", statisticItem);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StatisticsModel", Name="Run")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Run : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Run object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="label">Initial value of the Label property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        public static Run CreateRun(global::System.Int32 id, global::System.String label, global::System.DateTime startTime)
        {
            Run run = new Run();
            run.Id = id;
            run.Label = label;
            run.StartTime = startTime;
            return run;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, false, "Label");
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StatisticsModel", "FK_StatisticLogs_Runs", "StatisticLog1")]
        public EntityCollection<StatisticLog> StatisticLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StatisticLog>("StatisticsModel.FK_StatisticLogs_Runs", "StatisticLog1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StatisticLog>("StatisticsModel.FK_StatisticLogs_Runs", "StatisticLog1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StatisticsModel", Name="StatisticItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatisticItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatisticItem object.
        /// </summary>
        /// <param name="statisticName">Initial value of the StatisticName property.</param>
        public static StatisticItem CreateStatisticItem(global::System.String statisticName)
        {
            StatisticItem statisticItem = new StatisticItem();
            statisticItem.StatisticName = statisticName;
            return statisticItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatisticName
        {
            get
            {
                return _StatisticName;
            }
            set
            {
                if (_StatisticName != value)
                {
                    OnStatisticNameChanging(value);
                    ReportPropertyChanging("StatisticName");
                    _StatisticName = StructuralObject.SetValidValue(value, false, "StatisticName");
                    ReportPropertyChanged("StatisticName");
                    OnStatisticNameChanged();
                }
            }
        }
        private global::System.String _StatisticName;
        partial void OnStatisticNameChanging(global::System.String value);
        partial void OnStatisticNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StatisticsModel", "FK_StatisticLogs_Statistics", "StatisticLog")]
        public EntityCollection<StatisticLog> StatisticLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StatisticLog>("StatisticsModel.FK_StatisticLogs_Statistics", "StatisticLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StatisticLog>("StatisticsModel.FK_StatisticLogs_Statistics", "StatisticLog", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StatisticsModel", Name="StatisticLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatisticLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatisticLog object.
        /// </summary>
        /// <param name="runId">Initial value of the RunId property.</param>
        /// <param name="logId">Initial value of the LogId property.</param>
        /// <param name="logTime">Initial value of the LogTime property.</param>
        /// <param name="statisticName">Initial value of the StatisticName property.</param>
        /// <param name="statisticValue">Initial value of the StatisticValue property.</param>
        /// <param name="populationIndex">Initial value of the PopulationIndex property.</param>
        /// <param name="generationIndex">Initial value of the GenerationIndex property.</param>
        public static StatisticLog CreateStatisticLog(global::System.Int32 runId, global::System.Int32 logId, global::System.DateTime logTime, global::System.String statisticName, global::System.String statisticValue, global::System.Int32 populationIndex, global::System.Int32 generationIndex)
        {
            StatisticLog statisticLog = new StatisticLog();
            statisticLog.RunId = runId;
            statisticLog.LogId = logId;
            statisticLog.LogTime = logTime;
            statisticLog.StatisticName = statisticName;
            statisticLog.StatisticValue = statisticValue;
            statisticLog.PopulationIndex = populationIndex;
            statisticLog.GenerationIndex = generationIndex;
            return statisticLog;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RunId
        {
            get
            {
                return _RunId;
            }
            set
            {
                if (_RunId != value)
                {
                    OnRunIdChanging(value);
                    ReportPropertyChanging("RunId");
                    _RunId = StructuralObject.SetValidValue(value, "RunId");
                    ReportPropertyChanged("RunId");
                    OnRunIdChanged();
                }
            }
        }
        private global::System.Int32 _RunId;
        partial void OnRunIdChanging(global::System.Int32 value);
        partial void OnRunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogId
        {
            get
            {
                return _LogId;
            }
            set
            {
                if (_LogId != value)
                {
                    OnLogIdChanging(value);
                    ReportPropertyChanging("LogId");
                    _LogId = StructuralObject.SetValidValue(value, "LogId");
                    ReportPropertyChanged("LogId");
                    OnLogIdChanged();
                }
            }
        }
        private global::System.Int32 _LogId;
        partial void OnLogIdChanging(global::System.Int32 value);
        partial void OnLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LogTime
        {
            get
            {
                return _LogTime;
            }
            set
            {
                OnLogTimeChanging(value);
                ReportPropertyChanging("LogTime");
                _LogTime = StructuralObject.SetValidValue(value, "LogTime");
                ReportPropertyChanged("LogTime");
                OnLogTimeChanged();
            }
        }
        private global::System.DateTime _LogTime;
        partial void OnLogTimeChanging(global::System.DateTime value);
        partial void OnLogTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatisticName
        {
            get
            {
                return _StatisticName;
            }
            set
            {
                OnStatisticNameChanging(value);
                ReportPropertyChanging("StatisticName");
                _StatisticName = StructuralObject.SetValidValue(value, false, "StatisticName");
                ReportPropertyChanged("StatisticName");
                OnStatisticNameChanged();
            }
        }
        private global::System.String _StatisticName;
        partial void OnStatisticNameChanging(global::System.String value);
        partial void OnStatisticNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatisticValue
        {
            get
            {
                return _StatisticValue;
            }
            set
            {
                OnStatisticValueChanging(value);
                ReportPropertyChanging("StatisticValue");
                _StatisticValue = StructuralObject.SetValidValue(value, false, "StatisticValue");
                ReportPropertyChanged("StatisticValue");
                OnStatisticValueChanged();
            }
        }
        private global::System.String _StatisticValue;
        partial void OnStatisticValueChanging(global::System.String value);
        partial void OnStatisticValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PopulationIndex
        {
            get
            {
                return _PopulationIndex;
            }
            set
            {
                OnPopulationIndexChanging(value);
                ReportPropertyChanging("PopulationIndex");
                _PopulationIndex = StructuralObject.SetValidValue(value, "PopulationIndex");
                ReportPropertyChanged("PopulationIndex");
                OnPopulationIndexChanged();
            }
        }
        private global::System.Int32 _PopulationIndex;
        partial void OnPopulationIndexChanging(global::System.Int32 value);
        partial void OnPopulationIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenerationIndex
        {
            get
            {
                return _GenerationIndex;
            }
            set
            {
                OnGenerationIndexChanging(value);
                ReportPropertyChanging("GenerationIndex");
                _GenerationIndex = StructuralObject.SetValidValue(value, "GenerationIndex");
                ReportPropertyChanged("GenerationIndex");
                OnGenerationIndexChanged();
            }
        }
        private global::System.Int32 _GenerationIndex;
        partial void OnGenerationIndexChanging(global::System.Int32 value);
        partial void OnGenerationIndexChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StatisticsModel", "FK_StatisticLogs_Runs", "Run")]
        public Run Run
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Run>("StatisticsModel.FK_StatisticLogs_Runs", "Run").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Run>("StatisticsModel.FK_StatisticLogs_Runs", "Run").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Run> RunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Run>("StatisticsModel.FK_StatisticLogs_Runs", "Run");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Run>("StatisticsModel.FK_StatisticLogs_Runs", "Run", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StatisticsModel", "FK_StatisticLogs_Statistics", "Statistic")]
        public StatisticItem Statistic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatisticItem>("StatisticsModel.FK_StatisticLogs_Statistics", "Statistic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatisticItem>("StatisticsModel.FK_StatisticLogs_Statistics", "Statistic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StatisticItem> StatisticReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StatisticItem>("StatisticsModel.FK_StatisticLogs_Statistics", "Statistic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StatisticItem>("StatisticsModel.FK_StatisticLogs_Statistics", "Statistic", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
