//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFx.ComponentLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenFx.ComponentLibrary.Properties.LibResources", typeof(LibResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of this binary string cannot be changed..
        /// </summary>
        internal static string ErrorMsg_BinaryStringEntityLengthCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorMsg_BinaryStringEntityLengthCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation in {0} resulted in overflow.  This can often happen if Temperature setting is less than one..
        /// </summary>
        internal static string ErrorMsg_BoltzmannTotalOverflow {
            get {
                return ResourceManager.GetString("ErrorMsg_BoltzmannTotalOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or empty..
        /// </summary>
        internal static string ErrorMsg_EmptyList {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent node must belong to a tree before child nodes can be added..
        /// </summary>
        internal static string ErrorMsg_InsertChildNodeWithoutTree {
            get {
                return ResourceManager.GetString("ErrorMsg_InsertChildNodeWithoutTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;{0}&apos; must be a fixed integer count greater than 0 or an integral percentage between 1 and 100..
        /// </summary>
        internal static string ErrorMsg_InvalidPopulationReplacementValue {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidPopulationReplacementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; setting must be a valid {1} value.  The value provided was &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorMsg_InvalidTimeLimit {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be greater than or equal to zero..
        /// </summary>
        internal static string ErrorMsg_InvalidWheelSliceSize {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidWheelSliceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of this list cannot be changed..
        /// </summary>
        internal static string ErrorMsg_ListEntityLengthCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorMsg_ListEntityLengthCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorMsg_MismatchedMinMaxValues {
            get {
                return ResourceManager.GetString("ErrorMsg_MismatchedMinMaxValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only binary values (zero or one) are allowed..
        /// </summary>
        internal static string ErrorMsg_NonBinaryValueUsed {
            get {
                return ResourceManager.GetString("ErrorMsg_NonBinaryValueUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null item was contained in the list..
        /// </summary>
        internal static string ErrorMsg_NullItemInList {
            get {
                return ResourceManager.GetString("ErrorMsg_NullItemInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of objects to be replaced must be a non-negative integer.  The value provided was &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMsg_PopulationReplacementValue_LessThanZero {
            get {
                return ResourceManager.GetString("ErrorMsg_PopulationReplacementValue_LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node does not belong to this tree..
        /// </summary>
        internal static string ErrorMsg_SwapNodeNotInTree {
            get {
                return ResourceManager.GetString("ErrorMsg_SwapNodeNotInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be greater or equal to zero and less than or equal to the length..
        /// </summary>
        internal static string ErrorMsg_VariableLengthListEntity_InsertBit_OutOfRange {
            get {
                return ResourceManager.GetString("ErrorMsg_VariableLengthListEntity_InsertBit_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be greater or equal to zero and less than the length..
        /// </summary>
        internal static string ErrorMsg_VariableLengthListEntity_RemoveBit_OutOfRange {
            get {
                return ResourceManager.GetString("ErrorMsg_VariableLengthListEntity_RemoveBit_OutOfRange", resourceCulture);
            }
        }
    }
}
